// <auto-generated />
using System;
using JacksonVeroneze.ViaCep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JacksonVeroneze.ViaCep.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20201017122415_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JacksonVeroneze.ViaCep.Domain.Entities.Cep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnName("bairro")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Complemento")
                        .HasColumnName("complemento")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnName("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Ddd")
                        .HasColumnName("ddd")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnName("deleted_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gia")
                        .HasColumnName("gia")
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Ibge")
                        .HasColumnName("ibge")
                        .HasColumnType("int");

                    b.Property<string>("Localidade")
                        .HasColumnName("localidade")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Logradouro")
                        .HasColumnName("logradouro")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Numero")
                        .HasColumnName("numero")
                        .HasColumnType("char(9)");

                    b.Property<int>("Siafi")
                        .HasColumnName("siafi")
                        .HasColumnType("int");

                    b.Property<string>("Uf")
                        .HasColumnName("uf")
                        .HasColumnType("char(2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnName("updated_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnName("version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("cep");
                });
#pragma warning restore 612, 618
        }
    }
}
